"""post table

Revision ID: 02cff245a9e5
Revises: 0acf4c156113
Create Date: 2024-04-15 17:42:31.807031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02cff245a9e5'
down_revision = '0acf4c156113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('performance', schema=None) as batch_op:
        batch_op.alter_column('wins',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('losses',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('draws',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance', schema=None) as batch_op:
        batch_op.alter_column('draws',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('losses',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('wins',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=True)

    op.drop_table('post')
    # ### end Alembic commands ###
