"""editplayer and last_seen feilds

Revision ID: 2965e7efdcc9
Revises: e623897c3254
Create Date: 2024-05-09 12:49:39.957153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2965e7efdcc9'
down_revision = 'e623897c3254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('editplayer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=True),
    sa.Column('lastname', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('attendance', sa.String(length=200), nullable=True),
    sa.Column('fitness', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('editplayer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_editplayer_attendance'), ['attendance'], unique=False)
        batch_op.create_index(batch_op.f('ix_editplayer_date_of_birth'), ['date_of_birth'], unique=False)
        batch_op.create_index(batch_op.f('ix_editplayer_firstname'), ['firstname'], unique=False)
        batch_op.create_index(batch_op.f('ix_editplayer_fitness'), ['fitness'], unique=False)
        batch_op.create_index(batch_op.f('ix_editplayer_lastname'), ['lastname'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editplayer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_editplayer_lastname'))
        batch_op.drop_index(batch_op.f('ix_editplayer_fitness'))
        batch_op.drop_index(batch_op.f('ix_editplayer_firstname'))
        batch_op.drop_index(batch_op.f('ix_editplayer_date_of_birth'))
        batch_op.drop_index(batch_op.f('ix_editplayer_attendance'))

    op.drop_table('editplayer')
    # ### end Alembic commands ###
