"""EditPlayer Table

Revision ID: 78434a196201
Revises: 2965e7efdcc9
Create Date: 2024-05-09 16:31:01.269978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78434a196201'
down_revision = '2965e7efdcc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edit_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=True),
    sa.Column('lastname', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('attendance', sa.String(length=200), nullable=True),
    sa.Column('fitness', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('edit_player', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edit_player_attendance'), ['attendance'], unique=False)
        batch_op.create_index(batch_op.f('ix_edit_player_date_of_birth'), ['date_of_birth'], unique=False)
        batch_op.create_index(batch_op.f('ix_edit_player_firstname'), ['firstname'], unique=False)
        batch_op.create_index(batch_op.f('ix_edit_player_fitness'), ['fitness'], unique=False)
        batch_op.create_index(batch_op.f('ix_edit_player_lastname'), ['lastname'], unique=False)

    with op.batch_alter_table('editplayer', schema=None) as batch_op:
        batch_op.drop_index('ix_editplayer_attendance')
        batch_op.drop_index('ix_editplayer_date_of_birth')
        batch_op.drop_index('ix_editplayer_firstname')
        batch_op.drop_index('ix_editplayer_fitness')
        batch_op.drop_index('ix_editplayer_lastname')

    op.drop_table('editplayer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('editplayer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=50), nullable=True),
    sa.Column('lastname', sa.VARCHAR(length=50), nullable=True),
    sa.Column('date_of_birth', sa.DATETIME(), nullable=True),
    sa.Column('attendance', sa.VARCHAR(length=200), nullable=True),
    sa.Column('fitness', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('editplayer', schema=None) as batch_op:
        batch_op.create_index('ix_editplayer_lastname', ['lastname'], unique=False)
        batch_op.create_index('ix_editplayer_fitness', ['fitness'], unique=False)
        batch_op.create_index('ix_editplayer_firstname', ['firstname'], unique=False)
        batch_op.create_index('ix_editplayer_date_of_birth', ['date_of_birth'], unique=False)
        batch_op.create_index('ix_editplayer_attendance', ['attendance'], unique=False)

    with op.batch_alter_table('edit_player', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edit_player_lastname'))
        batch_op.drop_index(batch_op.f('ix_edit_player_fitness'))
        batch_op.drop_index(batch_op.f('ix_edit_player_firstname'))
        batch_op.drop_index(batch_op.f('ix_edit_player_date_of_birth'))
        batch_op.drop_index(batch_op.f('ix_edit_player_attendance'))

    op.drop_table('edit_player')
    # ### end Alembic commands ###
